### PR TITLE
Handle diffs on windows

### LINKED ISSUE #28: Parsing of diffs on windows fails
Running the standard GNU diff tool on windows can produce diff output with CRLF line endings instead of LF line endings. This currently causes an error in this diff parser. 

To reproduce, run the go-diff diagnostic tool on the attached diff:
```
go-diff -f sample_diff_win.txt
```
and get the following error:
```
err read file(0): line 3, char 116: bad hunk header: @@ -1,3 +1,9 @@
```
The parser uses an in-built line reader instead of `bufio.Scanner` which does not strip trailing CR characters from lines (unlike `bufio.Scanner`)

[sample_diff_win.txt](https://github.com/sourcegraph/go-diff/files/2848965/sample_diff_win.txt)

### PR DESCRIPTION
**Pull request by crsdrw**
Running the standard diff tool on windows produces output with CRLF line endings.
Stripping trailing CR in the line reader utility prevents errors in diff parsing.

Fixes #28

### CODE REVIEW

File: diff/reader_util.go [hunk 1]
```diff
@@ -25,6 +24,14 @@ func readLine(r *bufio.Reader) ([]byte, error) {
...
 		return nil, err
 	}
-	line := bytes.TrimSuffix(line_, []byte{'\n'})
-	return line, nil
+	line := line_[0:len(line_)-1]
+	return dropCR(line), nil
+}
+
+// dropCR drops a terminal \r from the data.
+func dropCR(data []byte) []byte {
```
Comment (crsdrw) [inline diff/reader_util.go]: This is the function used by `bufio.ScanLines`

File: diff/reader_util.go [hunk 2]
```diff
@@ -25,6 +24,14 @@ func readLine(r *bufio.Reader) ([]byte, error) {
 	} else if err != nil {
 		return nil, err
 	}
-	line := bytes.TrimSuffix(line_, []byte{'\n'})
-	return line, nil
+	line := line_[0:len(line_)-1]
```
Comment (crsdrw) [inline diff/reader_util.go]: After successfully reading a line we can guarantee that `line_` has a trailing `'\n'`
