### PR TITLE
Remove unreachable code.

### LINKED ISSUE #7: Two cases of unreachable code.
This is fairly harmless, but `vet` reports 2 instances of unreachable code. It's causing the Travis build to fail.

```
$ go tool vet ./
diff/parse.go:369: unreachable code
diff/parse.go:441: unreachable code
```

### PR DESCRIPTION
**Pull request by shurcooL**
Fixes #7.
Fixes Travis build.

### CODE REVIEW

File: diff/parse.go [hunk 1]
```diff
@@ -365,7 +365,6 @@ func (r *HunksReader) ReadHunk() (*Hunk, error) {
 		if r.hunk == nil {
 			// Check for presence of hunk header.
 			if !bytes.HasPrefix(line, hunkPrefix) {
-				panic("X")
```
Comment (shurcooL) [inline diff/parse.go]: This looks like a debugging artifact that was unintentionally left in from commit 86544b82264c7c9e3433dddae90c31fc2a30f5ba.

File: diff/parse.go [hunk 2]
```diff
@@ -436,12 +435,6 @@ func (r *HunksReader) ReadHunk() (*Hunk, error) {
 			r.hunk.Body = append(r.hunk.Body, '\n')
 		}
 	}
-
-	// Final hunk is complete. But if we never saw a hunk in this call to ReadHunk, then it means we hit EOF.
-	if r.hunk != nil {
-		return r.hunk, nil
-	}
-	return nil, io.EOF
```
Comment (shurcooL) [inline diff/parse.go]: This looks like code unintentionally left behind after it's no longer needed. It was introduced in commit https://github.com/sourcegraph/go-diff/commit/558247f853d5b5aa856bcab42659f40e895cae73#diff-b426b940498a3ecfc663fa2957b679f8R109, back when the `for {}` loop had a `break` in it.

Now, instead of that `break`, it performs this logic there instead. So removing this should be fine.

File: diff/parse.go (hunk 1 above)
Comment (slimsag) [inline diff/parse.go]: Good catch, that would've produced a pretty strange stack trace in that case :+1:

File: diff/parse.go (hunk 2 above)
Comment (slimsag) [inline diff/parse.go]: After removal of the line 444:

```
return nil, io.EOF
```

does the code compile? I assume it does, but I wouldn't have expected it to work without an explicit return or panic at the end of the function.

**Comment by slimsag** [comment]
Aside from [my comment](https://github.com/sourcegraph/go-diff/pull/8#discussion_r30382222) (which is mostly just my personal uncertainty) it all LGTM

File: diff/parse.go (hunk 2 above)
Comment (shurcooL) [inline diff/parse.go]: Yes, it compiles in Go 1.4 and later (maybe 1.3 too, I forget when they improved unreachable code detection). Travis would fail if it did not compile.

Comment (slimsag) [inline diff/parse.go]: I see; that makes sense. LGTM :)
