### PR TITLE
Fix parsing of non-extended file headers and lines starting with --

### LINKED ISSUE #54: nil-panic when parsing diffs in which lines starting with `--` were removed
PR https://github.com/sourcegraph/go-diff/pull/53 introduced behaviour that tries to detect new file headers while parsing hunks.

The problem is that it breaks the parsing of diffs like these:

```diff
diff --git a/foobar.sql b/foobar.sql
index 55140ba..236cd59 100644
--- a/foobar.sql
+++ b/foobar.sql
@@ -1,4 +1,3 @@
 select 1;
--- this is my query
 select 2;
 select 3;
```

If we try to parse this we get a nil-panic:

```
goroutine 20 [running]:
testing.tRunner.func1.1(0x11af8c0, 0x130cc70)
        /Users/thorstenball/.asdf/installs/golang/1.15/go/src/testing/testing.go:1057 +0x30d
testing.tRunner.func1(0xc00021e480)
        /Users/thorstenball/.asdf/installs/golang/1.15/go/src/testing/testing.go:1060 +0x41a
panic(0x11af8c0, 0x130cc70)
        /Users/thorstenball/.asdf/installs/golang/1.15/go/src/runtime/panic.go:969 +0x175
github.com/sourcegraph/go-diff/diff.(*MultiFileDiffReader).ReadFile(0xc000104ee8, 0x0, 0x0, 0x0)
        /Users/thorstenball/work/go-diff/diff/parse.go:77 +0x193
github.com/sourcegraph/go-diff/diff.TestParseWithoutNilPanic(0xc00021e480)
        /Users/thorstenball/work/go-diff/diff/diff_test.go:900 +0x2e7
testing.tRunner(0xc00021e480, 0x11e81e0)
        /Users/thorstenball/.asdf/installs/golang/1.15/go/src/testing/testing.go:1108 +0xef
created by testing.(*T).Run
        /Users/thorstenball/.asdf/installs/golang/1.15/go/src/testing/testing.go:1159 +0x386
FAIL    github.com/sourcegraph/go-diff/diff     0.161s
FAIL
```

The nil panic comes from a missing return here:

https://github.com/sourcegraph/go-diff/blob/96789e3401eadc2247f02d416dc90be9ccd98962/diff/parse.go#L60-L64

But the underlying cause is that we abort the parsing of the diff once we hit the `--`.

### PR DESCRIPTION
**Pull request by mrnugget**
This fixes #54 by making the detection of non-extended file headers
(which start with `---` directly) that was introduced in #53 more
robust.

Instead of simply aborting when the current line starts with `---`
(which is a valid hunk line, if you, say, remove a line starting with
`--`), we confirm that the next line also starts with `+++` by peeking a
bit ahead.

That's also what `git` does: https://sourcegraph.com/github.com/git/git/-/blob/apply.c#L1574-1576

### CODE REVIEW

File: diff/parse.go [hunk 1]
```diff
@@ -513,9 +514,22 @@ func (r *HunksReader) ReadHunk() (*Hunk, error) {
 			r.hunk.Section = section
 		} else {
 			// Read hunk body line.
+
+			// If the line starts with `---` and the next one with `+++` we're
+			// looking at a non-extended file header and need to abort.
+			if bytes.HasPrefix(line, []byte("---")) {
+				ok, err := nextLineHasPrefix(r.reader, []byte("+++"))
```
Comment (eseliger) [inline diff/parse.go:521]: would this fail with EOF when theres --- in the last line? (If that's even possible).

File: diff/testdata/sample_hunk_lines_start_with_minuses.diff [hunk 2]
```diff
@@ -0,0 +1,5 @@
+@@ -1,4 +1,3 @@
+ select 1;
+--- this is my query
+ select 2;
+ select 3;
```
Comment (eseliger) [inline diff/testdata/sample_hunk_lines_start_with_minuses.diff:5]:
```suggestion
@@ -1,4 +1,3 @@
 select 1;
--- this is my query
+++ this could break?
 select 2;
 select 3;
```

Comment (eseliger) [reply diff/testdata/sample_hunk_lines_start_with_minuses.diff:5]: Is that a case that works?

**Review by eseliger — APPROVED** [review]
Cool, 2 inline questions

File: diff/parse.go [hunk 3]
```diff
@@ -579,6 +593,16 @@ func linePrefix(c byte) bool {
 	return false
 }
 
+// nextLineHasPrefix peeks into the given reader to check whether the next
+// bytes match the given prefix.
+func nextLineHasPrefix(reader *bufio.Reader, prefix []byte) (bool, error) {
+	next, err := reader.Peek(len(prefix))
+	if err != nil {
```
Comment (keegancsmith) [inline diff/parse.go:600]: do we need to handle `ErrBufferFull`? I assume `len(prefix)` is always quite small.

> If Peek returns fewer than n bytes, it also returns an error explaining why the read is short

It seems like you need to handle that case. I assume by returning `false, nil`.  A test case for that would be great :)

File: diff/parse.go [hunk 4]
```diff
@@ -579,6 +593,16 @@ func linePrefix(c byte) bool {
 	return false
 }
 
+// nextLineHasPrefix peeks into the given reader to check whether the next
+// bytes match the given prefix.
+func nextLineHasPrefix(reader *bufio.Reader, prefix []byte) (bool, error) {
```
Comment (keegancsmith) [inline diff/parse.go:598]: this function is called `nextLineHasPrefix` but it seems to only do a peek, no line parsing/etc. It seems it being `nextLine` has more to do with the state of the reader at the time the function is called. I suggest a different name? Or maybe we can somewhat restructure this code to instead have an abstraction which just reads line by line and has a peekline function?

File: diff/parse.go [hunk 5]
```diff
@@ -579,6 +593,16 @@ func linePrefix(c byte) bool {
...
+	next, err := reader.Peek(len(prefix))
```
Comment (keegancsmith) [inline diff/parse.go:599]: is it possible that calling Peek affects the bytes previously returned? eg in some cases I know when using a reader it returns a slice directly from the buffer. So I'm worried about a call to peek mutating that buffer, which in turn mutates a slice that is used above. I'm not familiar enough with this code to know this offhand, so just calling it out since you mutated and should be able to say if this is safe.

**Review by keegancsmith — COMMENTED** [review]
some inline comments, not approving just yet :)

File: diff/testdata/sample_hunk_lines_start_with_minuses.diff (hunk 2 above)
Comment (mrnugget) [reply diff/testdata/sample_hunk_lines_start_with_minuses.diff:5]: You mean, with the fix here or in general?

Comment (eseliger) [reply diff/testdata/sample_hunk_lines_start_with_minuses.diff]: With the logic above that checks the next hunk line for `+++` and fails if it finds it.
Like when I change a line prefix from `--` to `++`, the diff would look like

```diff
line
---line
+++line
line
```
I guess. Would this be parseable?

File: diff/parse.go (hunk 1 above)
Comment (mrnugget) [reply diff/parse.go:521]: Yes! Fixed in 5726eda

File: diff/parse.go (hunk 4 above)
Comment (mrnugget) [reply diff/parse.go:598]: > I suggest a different name?

Good point, yeah. I'll do that.

> Or maybe we can somewhat restructure this code to instead have an abstraction which just reads line by line and has a peekline function?

I thought about that, but the way the rest of the code is structured doesn't make it easy. There's a ton of implicit caching and state involved that I don't want to touch (at least not in this PR). The best solution, IMHO, would be to wrap the `bufio.Reader` that's used here in a custom reader/scanner that stores current and peek lines.

File: diff/parse.go (hunk 3 above)
Comment (mrnugget) [reply diff/parse.go:600]: I just added a commit that checks for `io.EOF`, but I'm honestly not sure how to produce a test case that could make the code run into `ErrBufferFull`.

File: diff/parse.go (hunk 5 above)
Comment (mrnugget) [reply diff/parse.go:599]: I'm 99% sure this is safe. The code is not exactly straightforward, but as far as I can tell, the reader is only used to pass it to `readLine` and the resulting line slice is then modified cut in place. Having read through `Peek` and what it does, I can't see how it affects the previous read lines, _especially_ since we're on the new line.

File: diff/testdata/sample_hunk_lines_start_with_minuses.diff (hunk 2 above)
Comment (mrnugget) [reply diff/testdata/sample_hunk_lines_start_with_minuses.diff]: If I use this diff, it crashes:

```diff
diff --git a/foobar.sql b/foobar.sql
index 9537d7b..f73c856 100644
--- a/foobar.sql
+++ b/foobar.sql
@@ -1,5 +1,5 @@
 select 1;
--- this is my query
+++ this is my query
 select 2;
 select 3;
--- this is the last line
+++ this is the last line
```

I'll try to see if I can make that work.

**Review by keegancsmith — APPROVED** [review]

File: diff/testdata/sample_hunk_lines_start_with_minuses.diff (hunk 2 above)
Comment (mrnugget) [reply diff/testdata/sample_hunk_lines_start_with_minuses.diff]: @keegancsmith @eseliger what do you think of this? https://github.com/sourcegraph/go-diff/pull/56

It adds a custom type, `lineReader`, so we can do two-line lookahead and check whether the `---` and `+++` are followed by a `@@ `, which is what `git` does. It's built on top of this PR and all tests pass, including the case raised here by @eseliger.

**Comment by mrnugget** [comment]
I'm merging this and will take another stab at fixing the `--- foo\n+++ bar` problem in a separate PR, since that behaviour was never supported and this PR here is to intended to fix and restore old behaviour.
