### PR TITLE
Fix support for empty diffs (new, deleted, renamed, binary files).

### LINKED ISSUE #10: Add support for parsing multi-file diffs affecting binary files.
Unless I'm missing something, it seems the multi-file diff parser skips over changes to binary files (/cc @gbbr). Consider the following multi-file diff:

```diff
diff --git a/README.md b/README.md
index 7b73e04..36cde13 100644
--- a/README.md
+++ b/README.md
@@ -1,6 +1,8 @@
 Conception-go [![Build Status](https://travis-ci.org/shurcooL/Conception-go.svg?branch=master)](https://travis-ci.org/shurcooL/Conception-go)
 =============

+This is a change.
+
 This is a work in progress Go implementation of [Conception](https://github.com/shurcooL/Conception#demonstration).

 Conception is an experimental project. It's a platform for researching software development tools and techniques. It is driven by a set of guiding principles. Conception-go targets Go development.
diff --git a/data/Font.png b/data/Font.png
index 17a971d..599f8dd 100644
Binary files a/data/Font.png and b/data/Font.png differ
diff --git a/main.go b/main.go
index 1aced1e..98a982e 100644
--- a/main.go
+++ b/main.go
@@ -6710,6 +6710,8 @@ func init() {
 }

 func main() {
+	// Another plain text change.
+
 	//defer profile.Start(profile.CPUProfile).Stop()
 	//defer profile.Start(profile.MemProfile).Stop()

```

There are 3 files changed. Two text files (README.md and main.go), one binary file (data/Font.png).

However, if I execute `diff.ParseMultiFileDiff` on that diff, the output is a slice with just 2 `*diff.FileDiff` entries, for the two text files. The binary file change is not there.

#### Reproduce sample

```Go
package main

import (
	"fmt"
	"strings"

	"sourcegraph.com/sourcegraph/go-diff/diff"
)

// fileDiffName returns the name of a FileDiff.
func fileDiffName(fileDiff *diff.FileDiff) string {
	var origName, newName string
	if strings.HasPrefix(fileDiff.OrigName, "a/") {
		origName = fileDiff.OrigName[2:]
	}
	if strings.HasPrefix(fileDiff.NewName, "b/") {
		newName = fileDiff.NewName[2:]
	}
	switch {
	case origName != "" && newName != "" && origName == newName: // Modified.
		return newName
	case origName != "" && newName != "" && origName != newName: // Renamed.
		return origName + " -> " + newName
	case origName == "" && newName != "": // Added.
		return newName
	case origName != "" && newName == "": // Removed.
		return "~~" + origName + "~~"
	default:
		panic("unexpected, no names")
	}
}

func main() {
	b := []byte(input)
	var o string
	if fileDiffs, err := diff.ParseMultiFileDiff(b); err == nil {
		for _, fileDiff := range fileDiffs {
			o += "\n" + "## " + fileDiffName(fileDiff) + "\n"
			/*o += "\n```diff\n"
			if hunks, err := diff.PrintHunks(fileDiff.Hunks); err == nil {
				o += string(hunks)
			}
			o += "```\n"*/
		}
	} else {
		o += "\n```\n" + err.Error() + "\n```\n"
	}
	fmt.Println(o)
}

const input = `diff --git a/README.md b/README.md
index 7b73e04..36cde13 100644
--- a/README.md
+++ b/README.md
@@ -1,6 +1,8 @@
 Conception-go [![Build Status](https://travis-ci.org/shurcooL/Conception-go.svg?branch=master)](https://travis-ci.org/shurcooL/Conception-go)
 =============

+This is a change.
+
 This is a work in progress Go implementation of [Conception](https://github.com/shurcooL/Conception#demonstration).

 Conception is an experimental project. It's a platform for researching software development tools and techniques. It is driven by a set of guiding principles. Conception-go targets Go development.
diff --git a/data/Font.png b/data/Font.png
index 17a971d..599f8dd 100644
Binary files a/data/Font.png and b/data/Font.png differ
diff --git a/main.go b/main.go
index 1aced1e..98a982e 100644
--- a/main.go
+++ b/main.go
@@ -6710,6 +6710,8 @@ func init() {
 }

 func main() {
+	// Another plain text change.
+
 	//defer profile.Start(profile.CPUProfile).Stop()
 	//defer profile.Start(profile.MemProfile).Stop()

`
```

### PR DESCRIPTION
**Pull request by shurcooL**
~~DO NOT MERGE, this is a WIP PR and there are known TODOs to resolve. Early review (comments, suggestions) is welcome.~~ **Edit:** Ready for review and merge.

There are situations where a diff is empty. For example, if a blank file is added a removed. Or if a file is renamed without any changes. This change detects and handles those situations properly. **Edit:** Or if the file modified is binary.

Improve test coverage significantly.

~~TODO: Update .proto and regenerate .pb.go.~~

Fixes #10.

### CODE REVIEW

**Comment by shurcooL** [comment]
With the latest commit bcc6326c8eab8c04d10c598b2742c29891b878e8, I've finished cleaning up. This PR is ready for final review and merging (commits need to be squashed before merging).

File: diff/diff_test.go [hunk 1]
```diff
@@ -91,6 +94,268 @@ func TestParseHunksAndPrintHunks(t *testing.T) {
...
+			t.Fatal(err)
+		}
+		diff, err := ParseFileDiff(diffData)
+		if err != nil {
+			t.Fatalf("%s: got ParseFileDiff error %v", test.filename, err)
+		}
+
+		diff.Hunks = nil
+		if got, want := diff, test.wantDiff; !reflect.DeepEqual(got, want) {
+			t.Errorf("%s:\n\ngot: %v\nwant: %v", test.filename, goon.Sdump(got), goon.Sdump(want))
```
Comment (shurcooL) [inline diff/diff_test.go]: Could consider using [`github.com/d4l3k/messagediff`](https://github.com/d4l3k/messagediff#example-usage) here instead of printing 2 goons. It might be even more readable.

**Comment by beyang** [comment]
@shurcooL does this need to be code reviewed? If so, can you assign it to someone?

**Comment by shurcooL** [comment]
I'm quite confident about this change, but it needs to be reviewed because it's standard practice. I've assigned @slimsag since he has most context (he worked on it in https://github.com/sourcegraph/go-diff/issues/10#issuecomment-189775605).

File: diff/diff_test.go (hunk 1 above)
Comment (slimsag) [inline diff/diff_test.go]: Whatever you think is best; this is just a test dependency so adding dependencies is fine.

**Comment by slimsag** [comment]
LGTM
